version: "3.6"
services:
  linux:
    restart: always
    container_name: chatairunner_linux
    image: ghcr.io/capsize-games/chatairunner/chatairunner:linux
    user: root
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEV_ENV=0
      - CHATAIRUNNER_ENVIRONMENT=prod
      - CHATAIRUNNER_OS=linux
      - PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512
      - NUMBA_CACHE_DIR=/tmp/numba_cache
      - LD_LIBRARY_PATH=/usr/lib/python3.10:/usr/lib/x86_64-linux-gnu/:/usr/local/lib/:/usr/local/lib/python3.10:/usr/local/lib/python3.10/dist-packages
      - DISABLE_TELEMETRY=1
      - TCL_LIBDIR_PATH=/usr/lib/x86_64-linux-gnu/
      - TK_LIBDIR_PATH=/usr/lib/x86_64-linux-gnu/
    command: bash /app/build.sh