name: Build code

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}
      - name: Build with docker-compose build
        run: docker-compose build
      - name: Publish to itch with butler
        uses: itchio/butler-push-action@v1
        with:
          args: push dist/your_game_name your_game_name:your_game_version
          secrets:
              BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}